### ISSUE TITLE
Update Route Feature Toggle

### ISSUE THREAD

**Issue by jwicks31** [poetapp/explorer-web#160]
* [ ] Update Feature Toggle Wrapping `<Router>` 

### Comment From Kenny:
Saga in my opinion is the best because it keeps the view dumb, but a `Redirect` component isn't a terrible compromise for short term.

A `Redirect` component uses componentDidMount to change window.location, react-router 4 provides a [Redirect Component](https://reacttraining.com/react-router/web/api/Redirect), can't remember if the prev versions do or not. If not its super easy to create.

Here is a more concrete example of using a Redirect Components. Lets say we have for example a dashboard page that requires a logged in user.

We wrap the dashboard component with a `Feature` component and the if 'auth' feature is enabled, the `Feature` component will render the `Dashboard` else it will render a `Redirect` component and redirect once it mounts.

```js
import { Redirect } from 'react-router-dom'
import { Dashboard } from './Dashboard'
import { Feature } from '@paralleldrive/react-feature-toggles'

const RedirectToLogin = () => <Redirect to={{ pathname: '/login' }} />

export DashBoardPage = () => {
  <Feature name="auth" activeComponent={Dashboard} inactiveComponent={RedirectToLogin}>
}
```

Or we can use `configureFeature` for a bit more reusability

```js
import { Redirect } from 'react-router-dom'
import { Dashboard } from './Dashboard'
import { configureFeature } from '@paralleldrive/react-feature-toggles'

const RedirectToLogin = () => <Redirect to={{ pathname: '/login' }} />

const featureOrRedirectToLogin = configureFeature(RedirectToLogin) // save this in a separate file somewhere for reuse.

const authFeatureOrRedirect = featureOrRedirectToLogin('auth') // save this in another separate file somewhere for reuse.

const DashboardPage = authFeatureOrRedirect(Dashboard)
```

If we wanted to go beyond this by using sagas then this is how I handled it in the past. We create an AuthFeatureRedirect component that dispatches a special authFeatureRedirect action, create an authFeatureSaga that listens for that action and redirects as necessary. Completly removing the logic of how and where we redirect to from the view. 

In the past I used react-router-redux, so I would have the authFeatureSaga listen for the authFeatureRedirect action, then map that to the react-router-redux action `push` creator ( the push action creator changes window location). The benefits of using individual feature sagas that redirect through react-router-redux are:
- the individual feature saga can call more side effects, whereas if we used react-router-redux `push` directly from the component we would have no good way of performing those extra side effects for that feature.
- all redirect and route changes are react-router-redux `push` actions, so we can make listeners for those actions that log or push that data elsewhere like analytics.

**Comment by jwicks31** [comment]
I'm trying to implement this, but I'm having a little trouble seeing where we are checking to see if the user is logged in?

It seems like here we would just be checking to see if the feature 'auth' is enabled for a route. But really the feature toggle I was trying to implement is for the redirect portion of this router.

So whenever they go to the /login route it checks to see if the user is logged in and if they are they are redirected to the landing page. This is currently all it is doing, but eventually will have routes that are not accessible unless you are logged in.

**Comment by kennylavender** [comment]
a further question from @jwicks31 

> I'm trying to implement this, but I'm having a little trouble seeing where we are checking to see if the user is logged in?

> It seems like here we would just be checking to see if the feature 'auth' is enabled for a route. But really the feature toggle I was trying to implement is for the redirect portion of this router.

> So whenever they go to the /login route it checks to see if the user is logged in and if they are they are redirected to the landing page. This is currently all it is doing, but eventually will have routes that are not accessible unless you are logged in.

Routes should not be handling any logic other than routing. A Route component's job is to simply render the correct component for a specified route, that is all. What we do inside the route is up to the feature/page component. Logic like auth and feature toggles should not be handled above the route level. 

This is why in react-router 4, the onChange and onEnter props were removed from Route components. Its because they are unnecessary and not part of the Route component's job. Another example is looking at nextjs, nextjs does all the routing for you so that all you specify is page components, no routes, and no logic around the routes, any sort of auth or feature toggle logic needs to be specified by each page individually. The only things that belong above the route level are global things like context providers for the children of your routes. In nextjs that isn't even possible because you don't have access to the components above your routes.

So if a page component needs to redirect, or needs to show a 404, or requires a user to be logged in, then that is on the page component itself to implement.

Let's take my previous example with the Dashboard page a bit further, how can we compose all of this functionality together into a single page.


Here are the goals
- only show the dashaboard page if 'auth' feature toggle is active, else redirect to home page.
- dashboard page requires being logged in, show a 404 page if the user is not logged in
- if the user is logged in render the dashboard page.

```js
import { Redirect } from 'react-router-dom'
import { Feature } from '@paralleldrive/react-feature-toggles'
import { isActiveFeatureName } from '@paralleldrive/feature-toggles'

import { Layout } from './Layout'
import { Header } from './Header'
import { Sidebar } from './Sidebar'
import { Dashboard } from './Dashboard'
import { RequiresAuthentication } from './Authentication'

export const DashboardPage = () => {
  <Feature>
    {({ features }) => isActiveFeatureName('auth') ? (
      <RequiresAuthentication>  // renders 404 page instead of children if user is not logged in.
        <Layout>
          <Header />
          <SideBar />
          <DashBoard />
          <Footer />
        </Layout>
      </RequiresAuthentication>
    ) : (
      <Redirect to='/' />
    )}
  </Feature>
}
```

This same thing could be composed and broken apart in many different ways, above is just an example shouldn't be taken as the correct or only way to build a page.

We could simplify the process for ourselves a bit for pages that require the same features using higher order components

```js
import { Redirect } from 'react-router-dom'
import { Feature } from '@paralleldrive/react-feature-toggles'
import { isActiveFeatureName } from '@paralleldrive/feature-toggles'
import { compose } from 'ramda'

import { Layout } from './Layout'
import { Header } from './Header'
import { Sidebar } from './Sidebar'
import { Dashboard } from './Dashboard'
import { requiresAuthFeatureToggle } from './AuthFeatureToggle'
import { requiresAuthentication } from './Authentication'

const page = compose(
  requiresAuthFeatureToggle, // redirects if auth feature toggle is not enabled
  requiresAuthentication // renders 404 page instead of children if user is not logged in
)

const DashboardPageContents = () => {
  <Layout>
    <Header />
    <SideBar />
    <DashBoard />
    <Footer />
  </Layout>
}

export const DashboardPage = page(DashboardPageContents)
```

Now we can simply compose together our higher order components that we want to use in each page much quicker than writing them in JSX format. This also allows us to change and adjust the order of them much quicker.

**Comment by kennylavender** [comment]
Its good to remember that we don't want to build monolithic applications, we want to build mini applications that we compose together. Pages might have vastly different structures looks, functionality and needs, we don't want to couple them together. It might help to picture each page being its own independent mini application in a way. The routes just tell you which mini application to load.
