### ISSUE TITLE
Possible bug with Feature Toggles

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/explorer-web#179]
I think the `ft` query params isn't being re-read when a redirect is performed by the application rather than by the user, which leads to behavior such as:

- Register with FT 
- Get redirected to home without FT
- Still see things that should only be seen with FTs but URL has no FT

This behavior can be see in the [Angelou PR](https://github.com/poetapp/explorer-web/pull/151) and its [deploy preview](https://deploy-preview-151--poet-explorer.netlify.com/register?ft=nav-buttons,footer,register,auth,login).

@geoffturk @kennylavender

**Comment by kennylavender** [comment]
Good Catch. The function that is calculating features and `FeatureToggles` component needs to be inside the route so that it runs on route changes. It was designed to be wrapped around each page individually so the function runs on route changes. Not having used the library in a while myself I actually forgot about that, ¯\_(ツ)_/¯, but it should hopefully be an easy fix in the app. It's something we need to document in the library as well.

**Comment by geoffturk** [comment]
@jwicks31 Can you log this issue in the `react-feature-toggles` repo and then close it here when it is fixed? Thanks.

**Comment by kennylavender** [comment]
@geoffturk @jwicks31 as I explained above this is an issue with the app usage of react-feature-toggles. Not a react-feature-toggle bug.

**Comment by geoffturk** [comment]
@kennylavender OK, sorry. I missed that detail. 

Jesse has logged this in the RFT repo: https://github.com/paralleldrive/react-feature-toggles/issues/175

**Comment by geoffturk** [comment]
Reassigning to @jwicks31 so he can fix.

**Comment by kennylavender** [comment]
@geoffturk No worries :D

**Comment by ericelliott** [comment]
Reopen if this is still a pressing issue.
