### ISSUE TITLE
Bad UX in Sign Up / Email Confirmation

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/explorer-web#180]
When signing up in explorer, you're actually singing up in Frost.

Frost sends an automated email to confirm ownership of the email account doing the sign up.

To confirm, owner must follow a link in the email that leads them to frost.po.et. 

The issue at hand is that people will sign up at explorer.po.et but get redirected to frost.po.et. There isn't any message or link in Frost back to Explorer, so it's a dead end for users.

Fixing this will probably require changes to Frost API: support for dynamically setting the link. 

The only important part of that link is the Email Confirmation API Key Frost creates, which only the owner of the email account should have access to. Anyone with that token can call the API's verify-account endpoint.

Example verify-account url in emails: https://testing--frost.netlify.com/verified-account?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxhdXRhcm8rNTNAcG8uZXQiLCJjbGllbnRfdG9rZW4iOiI3OWIwMDRhNi1iMjYzLTA0MzYtYmMxOS00YTQ2ODdlNzk4NjgiLCJpYXQiOjE1MzM1MjI5NDh9.02hxCdvH20x30qyxAtshf_BtKqghTDJGgF8DXpJU6ME

It'd be probably be better UX, from the security standpoint, for the confirmation email's url to always point to the Frost Web, but passing a return-to url, and having Frost Web display a message such as: 

> Your email was confirmed successfully. It looks like you signed up via X. If this is correct, click here to go back to X. Otherwise please ignore or click here to report / whatever

Tagging:
- @jwicks31, author of https://github.com/poetapp/explorer-web/pull/151, the PR introducing Sign Up
- @wzalazar, author of everything Frost, for confirmation of my assumptions and overall feedback 
- @geoffturk for prioritization & overall feedback
- @wdavidturner for UX / product input

**Comment by wdavidturner** [comment]
I'll talk about it with @geoffturk in the AM.  I didn't realize you guys were starting work on things like this.

**Comment by lautarodragan** [comment]
Thanks @wdavidturner!

**Comment by geoffturk** [comment]
@wdavidturner It's part of the signup-signin feature under Angelou. We can discuss later today.

**Comment by wdavidturner** [comment]
Giving this some thought right now, but I want to be able to articulate how I'm prioritizing these things.

I've gone back and forth on having multiple locations to engage with Po.et at the start.  There's a pretty tight coupling here between some key components.

I'll work on something a little more put together.

**Comment by wzalazar** [comment]
Well, we can implement everything that we want. The only strong engage is the url in the email and it's maybe it changes depending on the domain was call it. I think it depends of what we want

For example, if we want can send the user to `explorer.po.et`. instead of `frost.po.et`. This is possible

in the `Frost api`, we need to add 1 new env var, and depending the domain take the base link for the email

`explore-web` will need to implement new page to handle it like as `frost web`

**Comment by geoffturk** [comment]
The aim is to keep user interactions via a web browser with Po.et pointed to `explorer.po.et` so Jesse should work toward this as he is working on the signup/signin flow.

@jwicks31 Ping me if you need more input on this.

**Comment by wdavidturner** [comment]
Be mindful of the UX pattern here when we don't own the applications.  For example, if we're expecting a third party to be able to engage with Po.et and allow someone to bring their own Frost API token with them, we need to explore the struggles that they'd have (similar to this).

I'm sure there's a way to shortcut the issue because we're hosting the applications on the same root domain, but we need to keep other applications in mind.

**Comment by lautarodragan** [comment]
Agreed. Ultimately, I think we may want to have Frost API implement a OAuth server or similar, and websites attempting to use a Frost sign-in should make a request the same way it's done for a Facebook login.

**Comment by geoffturk** [comment]
Some good discussion in the thread above. I think we're on the right track for all of it, and we have resolved the redirect issue that started this ticket with our release to Mainnet.
