### ISSUE TITLE
Work id available in API but not in explorer 

### ISSUE THREAD

**Issue by ar-anvd** [poetapp/explorer-web#295]
@lautarodragan Not sure if this issue is related with https://github.com/poetapp/explorer-web/issues/214

This work id has been timestamped 12 hours ago. It becomes available in API when doing:

`curl -H "Content-Type: application/json" -H "token: $FROST_TOKEN" -X GET $FROST_URL/works/513d40eab2bbd91799c37cb2b720a97312b370beaf170e6fe95ce8a07d3330f0`

However not available in explorer:

`https://explorer.po.et/works/513d40eab2bbd91799c37cb2b720a97312b370beaf170e6fe95ce8a07d3330f0`

Any reason for this mismatch? Anyway, this will lead to a broken url.

**Comment by lautarodragan** [comment]
Thanks for the bug report @ar-anvd!

This is most likely due to https://github.com/poetapp/node/issues/53.

We're working on fixing this at the moment.

**Comment by lautarodragan** [comment]
This is actually caused by some other issue.

```js
> db.works.find({id: '513d40eab2bbd91799c37cb2b720a97312b370beaf170e6fe95ce8a07d3330f0'}).pretty()
{
    "_id" : ObjectId("5b9881192934c414cb90c534"),
    "id" : "513d40eab2bbd91799c37cb2b720a97312b370beaf170e6fe95ce8a07d3330f0",
    "publicKey" : "0321e09fb342d297af0e1abc4841f44d72afef260e78427f34498c25ed28474482",
    "signature" : "304402203debf181b6a5c26220ff1ac412ee72be1820e4d789b54508130af0b8db91968802201ebc17ab6843adc230a0aa3faab289bf12f10f39e415b357cbece35a94f161b5",
    "type" : "Work",
    "dateCreated" : "2018-09-12T02:51:16.217Z",
    "attributes" : {
        "name" : "Boa para começar nada mais",
        "author" : "Teamlyzer Community",
        "tags" : "Teamlyzer, emprego, Glintt",
        "dateCreated" : "2018-09-10 22:27:09",
        "content" : "Boa para começar nada mais<ul>\n<li>Bom Ambiente</li>\n<li>Horário flexível</li>\n<li>Projetos interessantes</li>\n<li>Boa empresa para 1ºemprego.</li>\n</ul><ul>\n<li>Salário interessante inicialmente mas não há progressão do mesmo.</li>\n<li>Não há progressão na carreira.</li>\n<li>Pouco valorização dos séniores. Valorizam mais quem entra. Empresa para se estar no máximo 2anos.</li>\n</ul><p>Rating: 1.4/5.0</p> <p>CC BY-NC</p>",
        "datePublished" : "2018-09-12 01:27:46.519974"
    }
}
> db.storage.find({claimId: '513d40eab2bbd91799c37cb2b720a97312b370beaf170e6fe95ce8a07d3330f0'}).pretty()
{
    "_id" : ObjectId("5b9881192934c414cb90c532"),
    "claimId" : "513d40eab2bbd91799c37cb2b720a97312b370beaf170e6fe95ce8a07d3330f0",
    "ipfsHash" : "QmSuvredEuLPYP8a2EekoioJk8b5VJ3Q5vivAx7fwgW9ig"
}
> db.blockchainWriter.find({ipfsHash: 'QmSuvredEuLPYP8a2EekoioJk8b5VJ3Q5vivAx7fwgW9ig'}).pretty()
{
    "_id" : ObjectId("5b9881192934c414cb90c533"),
    "ipfsHash" : "QmSuvredEuLPYP8a2EekoioJk8b5VJ3Q5vivAx7fwgW9ig",
    "txId" : "f2f2adbc32afbc764b5c2c9b54b4929cea22e7521457dbe9ddb6fa292e6d9711"
}
```

https://ipfs.io/ipfs/QmSuvredEuLPYP8a2EekoioJk8b5VJ3Q5vivAx7fwgW9ig
https://test-insight.bitpay.com/api/tx/f2f2adbc32afbc764b5c2c9b54b4929cea22e7521457dbe9ddb6fa292e6d9711

This work was anchored in block 1413082, but the node explorer-web is using is lagging 413 blocks behind, at block 1412669. 

Maybe BlockchainReader crashed. The deployed version of the node is rather old, so no easy way to know for sure at the moment.

Let's keep this issue open and revisit in the future.

**Comment by ar-anvd** [comment]
@lautarodragan what this means in terms of functionality? 

The solution to keep using frost + po.et explorer is to wait for mainnet? 

-----------

I am willing to accept some errors at this stage, but unavailable work id, forever, is not acceptable even for a beta implementation of an immutable ledger explorer. 

E.g. 

- The user click in badge -> no available work id
- One hour later the user click in badge -> no available work id
- One day later the user click in badge -> no available work id
- And some "average joe" begins to doubt about the system/method

Don't you agree?

**Comment by ericelliott** [comment]
We are absolutely committed to making Po.et the most reliable way to secure creative work attribution that the world has ever seen.

We have fundamentally rearchitected how this process works in the upcoming mainnet release. The whole team is focused on making that available to you.

While hashing to testnet, you should not have an expectation that everything will work correctly. It is by definition a test deployment -- more of an early look at what's coming than production-ready software.

But don't worry -- we're making [swift progress on the mainnet release](https://blog.po.et/september-2018-po-et-engineering-progress-report-6d1751af7a84). We'll have it ready for you sometime in the coming weeks.

🍻

**Comment by lautarodragan** [comment]
Thanks Eric for jumping in.

@ar-anvd sorry for the delayed response. Everything Eric said is true — we're working hard to deliver a reliable Node, Frost and Explorer.

Just to clarify on the current situation: even though the work cannot be found in Explorer, it was correctly anchored by the node and Frost. This can be confirmed by my previous comment in this thread, showing at what Bitcoin block it was anchored and what IPFS hash it has. This is the most critical part, since it means that the work is safely stored.

I've again looked into this today and raised https://github.com/poetapp/node/issues/527, which is the underlying cause.

Update: the work is now available through the Explorer API, but still unavailable in Explorer Web. This looks like a cache issue with Netlify.

https://api.explorer.po.et/works/513d40eab2bbd91799c37cb2b720a97312b370beaf170e6fe95ce8a07d3330f0

**Comment by lautarodragan** [comment]
OK, so this is an issue caused by how we're fetching stuff from the API with Redux and using `redux-persist` to persist the redux state. We're rehydrating the redux state when we load the page from the saved state, not taking into account the fact that API responses may change over time.

Opening [Boa para começar nada mais](https://explorer.po.et/works/513d40eab2bbd91799c37cb2b720a97312b370beaf170e6fe95ce8a07d3330f0) on an Incognito window shows me work just fine, but on my usual Chrome it'll give me the `Work not found? It takes...` error message.

@jwicks31 @wzalazar can you guys confirm this theory?

@geoffturk we need to fix this for mainnet-beta. 

If how we're setting rehydration up is the root issue, we'll want to upgrade our strategy to support a TTL based on redux path.

**Comment by jwicks31** [comment]
@lautarodragan I believe you are correct about the issue. If you clear the site data in Chrome it will then load the work. You can verify that Redux is persisting the state because after you clear the data Redux DevTools in chrome shows the fetch request, but any other time it just shows that persist/REHYDRATE is the only action dispatched.
