### ISSUE TITLE
The specified account already exists.

### ISSUE THREAD

**Issue by ar-anvd** [poetapp/explorer-web#640]
Cant create new API accounts. Already tried a ton of different emails and passwords.

**Comment by lautarodragan** [comment]
@ar-anvd I can confirm the API will return an "account already exist" error for any account creation due to an error we're currently experiencing in our infrastructure, but the accounts I tried with where created still, and I was able to login with them. 

Can you try logging in to one one of the accounts you tried creating?

**Comment by ar-anvd** [comment]
@lautarodragan I confirm the account was created and I am able to login.  There is a strange V in top bar in all accounts.

**Comment by ar-anvd** [comment]
@lautarodragan well, **The specified account is not verified** when I try to make a new claim. This applies to all accounts. 

So this issue is a critical one and needs attention asap. Create a new claim is broken (tested with curl, python and web interface)

**Comment by lautarodragan** [comment]
Thank you @ar-anvd! We are aware this breaks the create claim feature for new accounts and are working on it.
